config/routes.rb
Rails.application.routes.draw do

  get 'chats/:id' => "chats#show", as: "chat"
  resources :chats, only: [:create] 
  get 'home/about'
  devise_for :users
  root to: "home#top"
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following
      get :follower
    end
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  post "follow/:id" => "relationships#follow", as: "follow"
  post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
  get "search" =>"search#search", as: "search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end


  attachment :profile_image
  validates :name,
    length: {in: 2..20},
    uniqueness: true
  validates :introduction, length: {maximum: 50}

#住所機能
  include JpPrefecture
  jp_prefecture :prefecture_code  #prefecture_codeはuserが持っているカラム

  #postal_codeからprefecture_nameに変換するメソッド
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
  end

  def follower
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table table_striped">
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
  </tr>
  <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.following_user.count %></td>
      <td>フォロワー数：<%= user.follower_user.count %></td>
      <% if user == current_user %>
        <td></td>
      <% elsif current_user.following?(user) %>
        <td><%= link_to "フォローを外す", unfollow_path(user), class: "text-dark", method: :post %></td>
      <% else %>
        <td><%= link_to "フォローする", follow_path(user), class: "text-dark", method: :post %></td>
      <% end %>
      <td><%= link_to "Show", user_path(user.id), class: "text-dark" %></td>
    </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
      <h1>User info</h1>
      <%= form_with model: @user, local: true do |f| %>
      <%= render "layouts/error_message", model: f.object %>

        <div class="form-group mb-3">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id: "inputName", placeholder: "名前", class: "d-block form-control" %>
        </div>
        <div class="form-group mb-3">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "d-block" %>
        </div>
        <div class="form-group mb-3">
          <label for="inputBody">Introduction</label>
          <%= f.text_area :introduction, placeholder: "コメント",class: "d-block form-control" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follower.html.erb
<h1>Follower Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following_user.count %></td>
        <td>フォロワー数：<%= user.follower_user.count %></td>
        <td><%= link_to "Show", user_path(user.id), class: "text-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/following.html.erb
<div class="container">
  <h1>Following Users</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      <% @user.following_user.where.not(id: current_user.id).each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.following_user.count %></td>
          <td>フォロワー数：<%= user.follower_user.count %></td>
          <td><%= link_to "Show", user_path(user), class: "text-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<%= render "layouts/error_message", model:@book %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/user_info", user:@user %>
      <%= render "layouts/new_book", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table table_striped">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.following_user.count %></td>
            <td>フォロワー数：<%= user.follower_user.count %></td>
            <% if user == current_user %>
              <td></td>
            <% elsif current_user.following?(user) %>
              <td><%= link_to "フォローを外す", unfollow_path(user), class: "text-dark", method: :post %></td>
            <% else %>
              <td><%= link_to "フォローする", follow_path(user), class: "text-dark", method: :post %></td>
            <% end %>
            <td><%= link_to "Show", user_path(user.id), class: "text-dark" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
</div><%= render "layouts/error_message", model:@book %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/user_info", user:@user %>
      <% if @user == current_user %>
      <% elsif current_user.following?(@user) %>
        <%= link_to "フォローを外す", unfollow_path(@user), class: "btn btn-sm btn-primary", method: :post %>
      <% else %>
        <%= link_to "フォローする", follow_path(@user), class: "btn btn-sm btn-success", method: :post %>
      <% end %>
      <%= render "layouts/new_book", book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table_striped">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40"  %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= "コメント#{book.book_comments.count}" %></td>
            <% if @user == current_user %>
              <td><%= link_to "Edit", edit_book_path(book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(book), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>