config/routes.rb
Rails.application.routes.draw do

  get 'chats/:id' => "chats#show", as: "chat"
  resources :chats, only: [:create] 
  get 'home/about'
  devise_for :users
  root to: "home#top"
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following
      get :follower
    end
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  post "follow/:id" => "relationships#follow", as: "follow"
  post "unfollow/:id" => "relationships#unfollow", as: "unfollow"
  get "search" =>"search#search", as: "search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body,
    presence: true,
    length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end


  attachment :profile_image
  validates :name,
    length: {in: 2..20},
    uniqueness: true
  validates :introduction, length: {maximum: 50}

#住所機能
  include JpPrefecture
  jp_prefecture :prefecture_code  #prefecture_codeはuserが持っているカラム

  #postal_codeからprefecture_nameに変換するメソッド
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_book, only: [:edit]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render "books/index"
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.new
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path
    else
      # ブラウザバックで戻った際にエラー表示が出る為以下追記
      redirect_to user_path(current_user)
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_book
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: @user.id, room_id: @room.id)
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top

  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
  end

  def follower
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <p><%= model.errors.count %>error prohibited this obj from being saved:</p>
  <% model.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/_new_book.html.erb
<div class="container mx-1">
  <h1>New book</h1>
<!--↓変更必要?-->
  <%= form_with model: book, url: books_path, local: true do |f| %>
    <div class="form-group mb-3">
      <p>Title</p>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group mb-3">
      <p>Opinion</p>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.submit "Create Book", class: "btn btn-sm btn-success" %>
    </div>
  <% end %>
</div>

app/views/layouts/_table_show.html.erb
<tr>
  <td><%= attachment_image_tag model.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"  %>
    <p><%= link_to model.user.name, user_path(model.user) %></p>
  </td>
  <td><%= link_to model.title, book_path(model) %></td>
  <td><%= model.body %></td>
  <% if model.user == current_user %>
    <td><%= link_to "Edit", edit_book_path(model) %></td>
    <td><%= link_to "Destroy", book_path(model), method: :delete %></td>
  <% end %>
</tr>

app/views/layouts/_user_info.html.erb
<div class="container mx-1">
    <h1>User info</h1>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: "jpg", fallback: "no_image.jpg" %>
    <table class="table table_striped">
        <tr>
            <th>name</th>
            <td><%= user.name %></td>
        </tr>
        <tr>
            <th>introduction</th>
            <td><%= user.introduction %></td>
        </tr>
        <tr>
            <th>follows</th>
            <td><%= link_to user.following_user.count, following_user_path(user) %></td>
        </tr>
        <tr>
            <th>followers</th>
            <td><%= link_to user.follower_user.count, follower_user_path(user) %></td>
        </tr>
    </table>
</div>
<% if current_user != @user %>
  <%= link_to 'チャットする', chat_path(@user.id) %>
<% end %> 

<%= link_to edit_user_path(user), class: "btn btn-block btn-sm btn-outline-secondary mb-3" do %>
    <i class="fas fa-user-cog"></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!--headここまで-->

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark">
        <div class ="container">
          <div class="navbar-brand"><%= link_to "Bookers", root_path, class: "nav-link text-white" %></div>
          <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link text-white" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link text-white" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link text-white" do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-white" do %>
                <i class="fas fa-sign-out-alt"></i> Logout
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-white" do %>
              <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class: "nav-link text-white" do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link text-white" do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link text-white" do %>
                <i class="fas fa-sign-in-alt"></i> Login
              <% end %>
            </li>
          <% end %>
          </ul>
        </div>
      </nav>
      <div class="text-success mb-3">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="text-center">
          <%= form_with scope: :search, url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :key_word %>
            <%= f.select :model, ["User","Book" ] %>
            <%= f.select :how, {"完全一致" => "match", "前方一致" => "forword", "後方一致" => "backword", "部分一致" => "partial"} %>
            <%= f.submit "検索" %>
            <% end %>
        </div>
      <% end %>
    </header>

<!--headerここまで-->
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/short_cut.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      
    </div>
    <div class="col-8 ml-auto">
      
    </div>
  </div>
</div>